apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-deployment
spec:
  selector:
    matchLabels:
      app: gw
  replicas: 1
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
        - name: gw
          image: ayach2024/sdci:main-gw
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_IP
              value: "server-clusterip"
            - name: SERVER_NAME
              value: "srv"
