apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1 
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ayach2024/sdci:server-app
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: APP_PERIOD
          value: "5000"
