apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone3-deployment
spec:
  selector:
    matchLabels:
      app: zone3
  replicas: 1
  template:
    metadata:
      labels:
        app: zone3
    spec:
      containers:
      - name: zone3
        image: ayach2024/sdci:zone
        ports:
        - containerPort: 8080
        env:
        - name: REMOTE_IP
          value: "gw-clusterip"
        - name: REMOTE_PORT
          value: "8080"
        - name: REMOTE_NAME
          value: "main-gw"
        - name: GATEWAY_NAME
          value: "GW3"
        - name: DEVICE_NAME
          value: "dev3" 
        - name: DEVICE_PERIOD
          value: "5000" 
